name = "nourish-api"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[[d1_databases]]
binding = "DB"
database_name = "nourish-db"
database_id = "c475cfb5-b866-4d51-a067-31648959a312"
migrations_dir = "migrations"

[vars]
APP_ORIGIN = "https://calorie-tracker-bot.pages.dev"

[triggers]
crons = ["0 * * * *"]
