import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const en = {
  common: { add: 'Add', close: 'Close', back: 'Back', continue: 'Continue', viewAll: 'View all', browse: 'Browse', items: 'items', meals: 'meals', days: 'days', kcal: 'kcal', saving: 'Saving...', adding: 'Adding...', system: 'System', english: 'English', russian: 'Russian' },
  nav: { today: 'Today', food: 'Food', progress: 'Progress', rewards: 'Rewards', profile: 'Profile' },
  greeting: { morning: 'Good morning, {{name}}', afternoon: 'Good afternoon, {{name}}', evening: 'Good evening, {{name}}' },
  dashboard: { dailyEnergy: 'Daily energy', calorieBalance: 'Calorie balance', streak: '{{count}} day streak', remaining: 'kcal remaining', consumed: 'Consumed', target: 'Daily target', protein: 'Protein', carbs: 'Carbs', fat: 'Fat', water: 'Water', level: 'Level {{level}}', totalXp: 'XP total', missions: "Today's missions", meals: "Today's meals", favorites: 'Favorites', breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner', snacks: 'Snacks', breakfastTime: '6:00 - 11:00', lunchTime: '11:00 - 15:00', dinnerTime: '17:00 - 22:00', anyTime: 'Any time' },
  food: { eyebrow: 'Nutrition library', title: 'Log food', searchPlaceholder: 'Search foods and meals', search: 'Search', favorites: 'Favorites', recent: 'Recent', saved: 'Saved', quickCalories: 'Quick calories', quickCaloriesCopy: 'Log calories without food details', customFood: 'Custom food', customFoodCopy: 'Create reusable nutrition', yourFavorites: 'Your favorites', recentlyLogged: 'Recently logged', suggested: 'Suggested foods', nothingHere: 'Nothing here yet', nothingHereCopy: 'Foods you mark will appear here.', savedMeals: 'Saved meals', noSaved: 'No saved meals yet', noSavedCopy: 'Create a custom food or combined meal to reuse it here.', createSaved: 'Create saved meal', addFavorite: 'Add favorite', removeFavorite: 'Remove favorite' },
  progress: { eyebrow: 'Health insights', title: 'Your progress', onTrack: 'On track', week: 'Week', month: 'Month', months3: '3 months', trend: '{{metric}} trend', average: '{{unit}} avg', calories: 'Calories', protein: 'Protein', carbs: 'Carbs', fat: 'Fat', water: 'Water', consistency: 'Consistency', daysLogged: 'days logged', avgCalories: 'Avg calories', perDay: 'per day', avgProtein: 'Avg protein', avgWater: 'Avg water', weightTrend: 'Weight trend', logWeight: "Log today's weight", periodAverage: 'Period average', weeklyAverage: 'Weekly average', goal: 'Goal', calorieConsistency: 'Calorie consistency', weightLogged: 'Weight logged', workerWeightError: 'Connect the Worker to save weight' },
  rewards: { eyebrow: 'Your momentum', title: 'Rewards', level: 'LEVEL {{level}}', untilLevel: '{{xp}} XP until level {{level}}', dayStreak: 'Day streak', bestStreak: 'Best streak', badges: 'Badges', dailyReady: 'Daily reward ready', dailyCopy: 'Open Nourish daily to grow your streak.', dailyMissions: 'Daily missions', weeklyMissions: 'Weekly missions', resetsMonday: 'Resets Monday', achievements: 'Achievements', earned: '{{count}} earned', freshStarter: 'Fresh Starter', habitBuilder: 'Habit Builder', wellnessPro: 'Wellness Pro', legend: 'Nourish Legend' },
  profile: { eyebrow: 'Your account', title: 'Profile', telegramMember: 'Telegram member', levelProgress: 'Level progress', weight: 'Weight', goal: 'Goal', badges: 'Badges', lose: 'Lose weight', gain: 'Gain weight', maintain: 'Maintain', appearance: 'Appearance', theme: 'Theme', light: 'Light', dark: 'Dark', preferences: 'Preferences', units: 'Units', unitsCopy: 'Weight, height, and water', metric: 'Metric', imperial: 'Imperial', language: 'Language', languageCopy: 'Choose the Mini App language', reminders: 'Reminders', dailyCheckin: 'Daily check-in', dailyCheckinCopy: 'Morning plan and motivation', waterReminder: 'Water reminder', waterReminderCopy: 'Gentle afternoon hydration nudge', calorieReminder: 'Calorie reminder', calorieReminderCopy: 'End-of-day target check', streakWarning: 'Streak warning', streakWarningCopy: 'Alert before your streak expires', yourData: 'Your data', export: 'Export all data', exportCopy: 'Download a complete JSON backup', delete: 'Delete all data', deleteCopy: 'Permanently remove your account', deleteConfirm: 'Delete all Nourish data? This cannot be undone.', exportDownloaded: 'Export downloaded', dataDeleted: 'Your data was deleted', connectExport: 'Connect the Worker to export data', connectDelete: 'Connect the Worker to delete data', footer: 'Nourish 1.0 · Built for Telegram' },
  onboarding: { title1: "Let's personalize your plan", copy1: 'A few details help us calculate targets that fit your body and routine.', age: 'Your age', years: 'years', gender: 'Gender', male: 'Male', female: 'Female', other: 'Other', title2: 'Your starting point', copy2: 'Use current measurements. You can update them any time from your profile.', height: 'Height', currentWeight: 'Current weight', targetWeight: 'Target weight', title3: 'Shape your daily plan', copy3: 'Choose the routine and goal that best reflect your life right now.', activity: 'ACTIVITY LEVEL', sedentary: 'Mostly seated', sedentaryCopy: 'Little intentional exercise', light: 'Lightly active', lightCopy: '1-3 workouts per week', moderate: 'Active', moderateCopy: '3-5 workouts per week', high: 'Very active', highCopy: '6-7 hard workouts', athlete: 'Athlete', athleteCopy: 'Intense training or physical work', yourGoal: 'YOUR GOAL', lose: 'Lose weight', loseCopy: 'A steady, sustainable calorie deficit', maintain: 'Maintain', maintainCopy: 'Keep your current weight and feel strong', gain: 'Gain weight', gainCopy: 'Build mass with a measured surplus', title4: 'Your plan is ready', copy4: 'Built from your metabolism, activity level, and goal. These targets can evolve with you.', perDay: 'kcal per day', waterGoal: 'Water goal', saveError: 'Could not save your plan. Check the Worker connection.', start: 'Start my journey', savingPlan: 'Saving your plan...' },
  overlay: { addToday: 'ADD TO TODAY', chooseFood: 'Choose food', customNutrition: 'Custom nutrition', searchFoods: 'Search foods', customQuick: 'Custom / quick', searchLibrary: 'Search your food library', servingDetails: 'Serving details', servings: 'Servings', each: '{{serving}} each', decreaseServings: 'Decrease servings', increaseServings: 'Increase servings', addTo: 'ADD TO', addKcal: 'Add {{calories}} kcal', foodName: 'Food name', foodExample: 'e.g. Homemade smoothie', calories: 'Calories', servingGrams: 'Serving grams', protein: 'Protein (g)', carbs: 'Carbs (g)', fat: 'Fat (g)', servingLabel: 'Serving label', saveCustom: 'Save to custom foods', saveCustomCopy: 'Available for faster logging next time', logCustom: 'Log custom food', addWater: 'Add water', afterAdding: 'after adding', waterRemaining: '{{amount}} ml remaining today', customAmount: 'CUSTOM AMOUNT', addMl: 'Add {{amount}} ml', mealLogged: 'Meal logged · +10 XP', waterAdded: 'Added {{amount}} ml water', connectMeals: 'Connect the Worker to save meals', connectWater: 'Connect the Worker to save water' },
  mealTypes: { breakfast: 'Breakfast', lunch: 'Lunch', dinner: 'Dinner', snack: 'Snack' },
  missions: { 'water-2l': { title: 'Hydration goal', description: 'Drink 2 liters of water' }, 'log-breakfast': { title: 'Morning momentum', description: 'Log your breakfast' }, 'protein-goal': { title: 'Protein target', description: 'Reach your daily protein goal' }, 'all-meals': { title: 'Full day logged', description: 'Log breakfast, lunch, and dinner' }, 'weekly-consistency': { title: 'Consistent week', description: 'Log food on five days this week' } },
  achievements: { 'first-meal': { title: 'First Meal', description: 'Log your first meal' }, 'healthy-week': { title: 'Healthy Week', description: 'Stay active for seven days' }, 'protein-master': { title: 'Protein Master', description: 'Reach protein target ten times' }, 'hydration-hero': { title: 'Hydration Hero', description: 'Reach water target ten times' }, 'consistency-king': { title: 'Consistency King', description: 'Build a 30-day streak' }, 'hundred-meals': { title: '100 Meals Logged', description: 'Log one hundred meals' }, 'goal-weight': { title: 'Goal Weight Achieved', description: 'Reach your target weight' } },
  foods: { 'food-eggs': 'Eggs', 'food-oats': 'Oatmeal', 'food-chicken': 'Chicken breast', 'food-rice': 'Basmati rice', 'food-yogurt': 'Greek yogurt', 'food-banana': 'Banana' },
};

const ru: typeof en = {
  common: { add: 'Добавить', close: 'Закрыть', back: 'Назад', continue: 'Продолжить', viewAll: 'Все', browse: 'Открыть', items: 'продуктов', meals: 'приёмов', days: 'дней', kcal: 'ккал', saving: 'Сохранение...', adding: 'Добавление...', system: 'Система', english: 'Английский', russian: 'Русский' },
  nav: { today: 'Сегодня', food: 'Еда', progress: 'Прогресс', rewards: 'Награды', profile: 'Профиль' },
  greeting: { morning: 'Доброе утро, {{name}}', afternoon: 'Добрый день, {{name}}', evening: 'Добрый вечер, {{name}}' },
  dashboard: { dailyEnergy: 'Энергия на день', calorieBalance: 'Баланс калорий', streak: 'Серия: {{count}} дн.', remaining: 'ккал осталось', consumed: 'Съедено', target: 'Цель на день', protein: 'Белки', carbs: 'Углеводы', fat: 'Жиры', water: 'Вода', level: 'Уровень {{level}}', totalXp: 'Всего XP', missions: 'Задания на сегодня', meals: 'Сегодняшние приёмы пищи', favorites: 'Избранное', breakfast: 'Завтрак', lunch: 'Обед', dinner: 'Ужин', snacks: 'Перекусы', breakfastTime: '6:00 - 11:00', lunchTime: '11:00 - 15:00', dinnerTime: '17:00 - 22:00', anyTime: 'В любое время' },
  food: { eyebrow: 'Библиотека питания', title: 'Добавить еду', searchPlaceholder: 'Поиск продуктов и блюд', search: 'Поиск', favorites: 'Избранное', recent: 'Недавние', saved: 'Сохранённые', quickCalories: 'Быстрые калории', quickCaloriesCopy: 'Записать калории без деталей', customFood: 'Свой продукт', customFoodCopy: 'Создать продукт для повторного использования', yourFavorites: 'Ваше избранное', recentlyLogged: 'Недавно добавленные', suggested: 'Рекомендуемые продукты', nothingHere: 'Здесь пока пусто', nothingHereCopy: 'Отмеченные продукты появятся здесь.', savedMeals: 'Сохранённые блюда', noSaved: 'Нет сохранённых блюд', noSavedCopy: 'Создайте свой продукт или блюдо, чтобы использовать его снова.', createSaved: 'Создать блюдо', addFavorite: 'В избранное', removeFavorite: 'Убрать из избранного' },
  progress: { eyebrow: 'Показатели здоровья', title: 'Ваш прогресс', onTrack: 'Всё по плану', week: 'Неделя', month: 'Месяц', months3: '3 месяца', trend: 'Динамика: {{metric}}', average: 'в среднем {{unit}}', calories: 'Калории', protein: 'Белки', carbs: 'Углеводы', fat: 'Жиры', water: 'Вода', consistency: 'Регулярность', daysLogged: 'дней заполнено', avgCalories: 'Средние калории', perDay: 'в день', avgProtein: 'Средние белки', avgWater: 'Средняя вода', weightTrend: 'Динамика веса', logWeight: 'Записать вес сегодня', periodAverage: 'Среднее за период', weeklyAverage: 'Среднее за неделю', goal: 'Цель', calorieConsistency: 'Регулярность калорий', weightLogged: 'Вес записан', workerWeightError: 'Подключите Worker для сохранения веса' },
  rewards: { eyebrow: 'Ваш ритм', title: 'Награды', level: 'УРОВЕНЬ {{level}}', untilLevel: '{{xp}} XP до уровня {{level}}', dayStreak: 'Серия дней', bestStreak: 'Лучшая серия', badges: 'Значки', dailyReady: 'Ежедневная награда', dailyCopy: 'Открывайте Nourish каждый день и растите серию.', dailyMissions: 'Задания на день', weeklyMissions: 'Задания на неделю', resetsMonday: 'Сброс в понедельник', achievements: 'Достижения', earned: 'Получено: {{count}}', freshStarter: 'Свежий старт', habitBuilder: 'Создатель привычек', wellnessPro: 'Эксперт здоровья', legend: 'Легенда Nourish' },
  profile: { eyebrow: 'Ваш аккаунт', title: 'Профиль', telegramMember: 'Пользователь Telegram', levelProgress: 'Прогресс уровня', weight: 'Вес', goal: 'Цель', badges: 'Значки', lose: 'Снижение веса', gain: 'Набор веса', maintain: 'Поддержание', appearance: 'Оформление', theme: 'Тема', light: 'Светлая', dark: 'Тёмная', preferences: 'Настройки', units: 'Единицы', unitsCopy: 'Вес, рост и вода', metric: 'Метрические', imperial: 'Имперские', language: 'Язык', languageCopy: 'Выберите язык приложения', reminders: 'Напоминания', dailyCheckin: 'Ежедневный план', dailyCheckinCopy: 'Утренний план и мотивация', waterReminder: 'Напоминание о воде', waterReminderCopy: 'Мягкое напоминание днём', calorieReminder: 'Напоминание о калориях', calorieReminderCopy: 'Проверка цели в конце дня', streakWarning: 'Предупреждение о серии', streakWarningCopy: 'Уведомить до потери серии', yourData: 'Ваши данные', export: 'Экспортировать данные', exportCopy: 'Скачать полную резервную копию JSON', delete: 'Удалить все данные', deleteCopy: 'Навсегда удалить аккаунт', deleteConfirm: 'Удалить все данные Nourish? Это действие нельзя отменить.', exportDownloaded: 'Экспорт скачан', dataDeleted: 'Ваши данные удалены', connectExport: 'Подключите Worker для экспорта', connectDelete: 'Подключите Worker для удаления данных', footer: 'Nourish 1.0 · Создано для Telegram' },
  onboarding: { title1: 'Настроим ваш план', copy1: 'Несколько данных помогут рассчитать цели под ваше тело и образ жизни.', age: 'Ваш возраст', years: 'лет', gender: 'Пол', male: 'Мужской', female: 'Женский', other: 'Другой', title2: 'Точка старта', copy2: 'Укажите текущие параметры. Их можно изменить в профиле.', height: 'Рост', currentWeight: 'Текущий вес', targetWeight: 'Целевой вес', title3: 'Составим план на день', copy3: 'Выберите активность и цель, которые соответствуют вашей жизни.', activity: 'УРОВЕНЬ АКТИВНОСТИ', sedentary: 'В основном сижу', sedentaryCopy: 'Мало физической активности', light: 'Лёгкая активность', lightCopy: '1-3 тренировки в неделю', moderate: 'Активный', moderateCopy: '3-5 тренировок в неделю', high: 'Очень активный', highCopy: '6-7 интенсивных тренировок', athlete: 'Спортсмен', athleteCopy: 'Интенсивные тренировки или физическая работа', yourGoal: 'ВАША ЦЕЛЬ', lose: 'Снизить вес', loseCopy: 'Устойчивый дефицит калорий', maintain: 'Поддерживать', maintainCopy: 'Сохранить вес и хорошее самочувствие', gain: 'Набрать вес', gainCopy: 'Контролируемый профицит для набора массы', title4: 'Ваш план готов', copy4: 'Он основан на обмене веществ, активности и цели и будет меняться вместе с вами.', perDay: 'ккал в день', waterGoal: 'Цель по воде', saveError: 'Не удалось сохранить план. Проверьте подключение Worker.', start: 'Начать', savingPlan: 'Сохраняем план...' },
  overlay: { addToday: 'ДОБАВИТЬ СЕГОДНЯ', chooseFood: 'Выберите продукт', customNutrition: 'Свои данные', searchFoods: 'Поиск продуктов', customQuick: 'Свой / быстро', searchLibrary: 'Поиск в библиотеке', servingDetails: 'Размер порции', servings: 'Порции', each: '{{serving}} каждая', decreaseServings: 'Уменьшить число порций', increaseServings: 'Увеличить число порций', addTo: 'ДОБАВИТЬ В', addKcal: 'Добавить {{calories}} ккал', foodName: 'Название продукта', foodExample: 'например, домашний смузи', calories: 'Калории', servingGrams: 'Вес порции', protein: 'Белки (г)', carbs: 'Углеводы (г)', fat: 'Жиры (г)', servingLabel: 'Название порции', saveCustom: 'Сохранить продукт', saveCustomCopy: 'Доступен для быстрого добавления', logCustom: 'Записать продукт', addWater: 'Добавить воду', afterAdding: 'после добавления', waterRemaining: 'Осталось {{amount}} мл на сегодня', customAmount: 'СВОЙ ОБЪЁМ', addMl: 'Добавить {{amount}} мл', mealLogged: 'Еда добавлена · +10 XP', waterAdded: 'Добавлено {{amount}} мл воды', connectMeals: 'Подключите Worker для сохранения еды', connectWater: 'Подключите Worker для сохранения воды' },
  mealTypes: { breakfast: 'Завтрак', lunch: 'Обед', dinner: 'Ужин', snack: 'Перекус' },
  missions: { 'water-2l': { title: 'Цель по воде', description: 'Выпить 2 литра воды' }, 'log-breakfast': { title: 'Утренний ритм', description: 'Записать завтрак' }, 'protein-goal': { title: 'Цель по белку', description: 'Достичь цели по белку' }, 'all-meals': { title: 'Полный день', description: 'Записать завтрак, обед и ужин' }, 'weekly-consistency': { title: 'Стабильная неделя', description: 'Записывать еду пять дней за неделю' } },
  achievements: { 'first-meal': { title: 'Первая еда', description: 'Записать первый приём пищи' }, 'healthy-week': { title: 'Здоровая неделя', description: 'Быть активным семь дней' }, 'protein-master': { title: 'Мастер белка', description: 'Достичь цели по белку десять раз' }, 'hydration-hero': { title: 'Герой воды', description: 'Достичь цели по воде десять раз' }, 'consistency-king': { title: 'Король регулярности', description: 'Серия в 30 дней' }, 'hundred-meals': { title: '100 приёмов пищи', description: 'Записать сто приёмов пищи' }, 'goal-weight': { title: 'Целевой вес', description: 'Достичь целевого веса' } },
  foods: { 'food-eggs': 'Яйца', 'food-oats': 'Овсянка', 'food-chicken': 'Куриная грудка', 'food-rice': 'Рис басмати', 'food-yogurt': 'Греческий йогурт', 'food-banana': 'Банан' },
};

const savedLanguage = localStorage.getItem('language');
const telegramLanguage = window.Telegram?.WebApp?.initDataUnsafe?.user?.language_code;
const detectedLanguage = savedLanguage ?? ([telegramLanguage, navigator.language].some((language) => language?.toLowerCase().startsWith('ru')) ? 'ru' : 'en');

void i18n.use(initReactI18next).init({
  resources: { en: { translation: en }, ru: { translation: ru } },
  lng: detectedLanguage,
  fallbackLng: 'en',
  interpolation: { escapeValue: false },
});

export default i18n;
