import type { ReactNode } from 'react';
import { motion } from 'framer-motion';
import { CalendarCheck, CalendarHeart, Check, Crown, Droplets, Dumbbell, Flame, Medal, Sparkles, Sunrise, Trophy, Utensils } from 'lucide-react';
import { cn, pct } from '@/lib/utils';

export const MotionButton=motion.button;
export function IconFor({name,className}:{name:string;className?:string}){const icons:Record<string,typeof Flame>={Droplets,Dumbbell,Sunrise,Utensils,CalendarCheck,CalendarHeart,Crown,Medal,Trophy,Flame,Sparkles};const Icon=icons[name]??Sparkles;return <Icon className={className}/>;}
export function PageHeader({eyebrow,title,action}:{eyebrow?:string;title:string;action?:ReactNode}){return <header className="mb-6 flex items-end justify-between"><div>{eyebrow&&<p className="mb-1 text-[13px] font-semibold text-blue">{eyebrow}</p>}<h1 className="font-display text-[29px] font-extrabold leading-tight tracking-normal">{title}</h1></div>{action}</header>}
export function SectionTitle({title,action}:{title:string;action?:ReactNode}){return <div className="mb-3 flex items-center justify-between"><h2 className="font-display text-[18px] font-bold tracking-normal">{title}</h2>{action}</div>}
export function Ring({value,target,size=164,stroke=13,color='#2787f5',children}:{value:number;target:number;size?:number;stroke?:number;color?:string;children?:ReactNode}){const radius=(size-stroke)/2;const circumference=2*Math.PI*radius;const progress=Math.min(1,value/Math.max(1,target));return <div className="relative shrink-0" style={{width:size,height:size}}><svg className="-rotate-90" width={size} height={size} aria-label={`${pct(value,target)} percent complete`}><circle cx={size/2} cy={size/2} r={radius} stroke="currentColor" strokeWidth={stroke} fill="none" className="text-[#e8eef5] dark:text-[#26313d]"/><motion.circle cx={size/2} cy={size/2} r={radius} stroke={color} strokeWidth={stroke} fill="none" strokeLinecap="round" strokeDasharray={circumference} initial={{strokeDashoffset:circumference}} animate={{strokeDashoffset:circumference*(1-progress)}} transition={{duration:.9,ease:[.2,.8,.2,1]}}/></svg><div className="absolute inset-0 flex items-center justify-center text-center">{children}</div></div>}
export function ProgressBar({value,target,color='bg-blue',className}:{value:number;target:number;color?:string;className?:string}){return <div className={cn('h-2 overflow-hidden rounded-full bg-[#e8eef5] dark:bg-[#26313d]',className)}><motion.div className={cn('h-full rounded-full',color)} initial={{width:0}} animate={{width:`${pct(value,target)}%`}} transition={{duration:.7,ease:'easeOut'}}/></div>}
export function Metric({label,value,target,unit,color}:{label:string;value:number;target:number;unit:string;color:string}){return <div className="min-w-0 flex-1"><div className="mb-2 flex items-baseline justify-between gap-2"><span className="truncate text-[12px] font-semibold subtle">{label}</span><span className="text-[12px] font-bold">{Math.round(value)}<span className="font-medium subtle">/{target}{unit}</span></span></div><ProgressBar value={value} target={target} color={color}/></div>}
export function Pill({children,tone='blue'}:{children:ReactNode;tone?:'blue'|'green'|'yellow'|'gray'}){const tones={blue:'bg-blue/10 text-blue',green:'bg-mint/12 text-[#149476]',yellow:'bg-sun/15 text-[#a56b00]',gray:'bg-[#edf1f5] text-[#66717e] dark:bg-[#27313c] dark:text-[#b4bec9]'};return <span className={cn('inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[12px] font-bold',tones[tone])}>{children}</span>}
export function EmptyState({icon,title,copy}:{icon:ReactNode;title:string;copy:string}){return <div className="card flex flex-col items-center px-7 py-9 text-center"><div className="mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-blue/10 text-blue">{icon}</div><h3 className="font-display text-[16px] font-bold">{title}</h3><p className="mt-1 max-w-[260px] text-[13px] leading-5 subtle">{copy}</p></div>}
export function Toggle({checked,onChange,label}:{checked:boolean;onChange:(checked:boolean)=>void;label:string}){return <button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={()=>onChange(!checked)} className={cn('relative h-7 w-12 rounded-full transition-colors',checked?'bg-blue':'bg-[#d7dfe8] dark:bg-[#34414f]')}><motion.span className="absolute top-1 h-5 w-5 rounded-full bg-white shadow" animate={{left:checked?24:4}}/></button>}
export function CompletedMark(){return <span className="flex h-7 w-7 items-center justify-center rounded-full bg-mint text-white"><Check size={16} strokeWidth={3}/></span>}
