PRAGMA foreign_keys = ON;
CREATE TABLE users (id TEXT PRIMARY KEY NOT NULL, telegram_id TEXT NOT NULL UNIQUE, first_name TEXT NOT NULL, last_name TEXT, username TEXT, avatar_url TEXT, age INTEGER, gender TEXT, height_cm REAL, current_weight_kg REAL, target_weight_kg REAL, activity_level TEXT, goal TEXT, calorie_target INTEGER NOT NULL DEFAULT 2000, protein_target INTEGER NOT NULL DEFAULT 120, carbs_target INTEGER NOT NULL DEFAULT 220, fat_target INTEGER NOT NULL DEFAULT 65, water_target_ml INTEGER NOT NULL DEFAULT 2200, onboarding_complete INTEGER NOT NULL DEFAULT 0, xp INTEGER NOT NULL DEFAULT 0, level INTEGER NOT NULL DEFAULT 1, coins INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX users_telegram_idx ON users(telegram_id);
CREATE TABLE foods (id TEXT PRIMARY KEY NOT NULL, user_id TEXT REFERENCES users(id) ON DELETE CASCADE, name TEXT NOT NULL, brand TEXT, serving_label TEXT NOT NULL DEFAULT '1 serving', serving_grams REAL NOT NULL DEFAULT 100, calories REAL NOT NULL, protein REAL NOT NULL DEFAULT 0, carbs REAL NOT NULL DEFAULT 0, fat REAL NOT NULL DEFAULT 0, is_favorite INTEGER NOT NULL DEFAULT 0, use_count INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX foods_name_idx ON foods(name); CREATE INDEX foods_user_idx ON foods(user_id);
CREATE TABLE meals (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, meal_type TEXT NOT NULL, name TEXT, logged_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE INDEX meals_user_date_idx ON meals(user_id, logged_at);
CREATE TABLE meal_items (id TEXT PRIMARY KEY NOT NULL, meal_id TEXT NOT NULL REFERENCES meals(id) ON DELETE CASCADE, food_id TEXT REFERENCES foods(id) ON DELETE SET NULL, food_name TEXT NOT NULL, serving_label TEXT NOT NULL, multiplier REAL NOT NULL DEFAULT 1, calories REAL NOT NULL, protein REAL NOT NULL, carbs REAL NOT NULL, fat REAL NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE INDEX meal_items_meal_idx ON meal_items(meal_id);
CREATE TABLE water_logs (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, amount_ml INTEGER NOT NULL, logged_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE INDEX water_user_date_idx ON water_logs(user_id, logged_at);
CREATE TABLE weight_logs (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, weight_kg REAL NOT NULL, logged_at TEXT NOT NULL, note TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE INDEX weight_user_date_idx ON weight_logs(user_id, logged_at);
CREATE TABLE daily_progress (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, date TEXT NOT NULL, calories REAL NOT NULL DEFAULT 0, protein REAL NOT NULL DEFAULT 0, carbs REAL NOT NULL DEFAULT 0, fat REAL NOT NULL DEFAULT 0, water_ml INTEGER NOT NULL DEFAULT 0, meals_logged INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE UNIQUE INDEX daily_progress_user_date_unique ON daily_progress(user_id, date);
CREATE TABLE missions (id TEXT PRIMARY KEY NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, icon TEXT NOT NULL, metric TEXT NOT NULL, target REAL NOT NULL, xp_reward INTEGER NOT NULL, coin_reward INTEGER NOT NULL DEFAULT 5, period TEXT NOT NULL DEFAULT 'daily', active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE completed_missions (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, mission_id TEXT NOT NULL REFERENCES missions(id) ON DELETE CASCADE, period_key TEXT NOT NULL, progress REAL NOT NULL DEFAULT 0, completed_at TEXT, claimed_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE UNIQUE INDEX completed_mission_period_unique ON completed_missions(user_id, mission_id, period_key);
CREATE TABLE achievements (id TEXT PRIMARY KEY NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, icon TEXT NOT NULL, metric TEXT NOT NULL, target REAL NOT NULL, xp_reward INTEGER NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE user_achievements (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, achievement_id TEXT NOT NULL REFERENCES achievements(id) ON DELETE CASCADE, unlocked_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL); CREATE UNIQUE INDEX user_achievement_unique ON user_achievements(user_id, achievement_id);
CREATE TABLE xp_logs (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, amount INTEGER NOT NULL, reason TEXT NOT NULL, reference_id TEXT, created_at TEXT NOT NULL); CREATE INDEX xp_user_idx ON xp_logs(user_id);
CREATE TABLE streaks (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, current_streak INTEGER NOT NULL DEFAULT 0, longest_streak INTEGER NOT NULL DEFAULT 0, last_active_date TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE settings (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, theme TEXT NOT NULL DEFAULT 'system', language TEXT NOT NULL DEFAULT 'en', units TEXT NOT NULL DEFAULT 'metric', daily_reminder INTEGER NOT NULL DEFAULT 1, water_reminder INTEGER NOT NULL DEFAULT 1, calorie_reminder INTEGER NOT NULL DEFAULT 1, streak_warning INTEGER NOT NULL DEFAULT 1, reminder_hour INTEGER NOT NULL DEFAULT 9, timezone TEXT NOT NULL DEFAULT 'UTC', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE sessions (id TEXT PRIMARY KEY NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, last_seen_at TEXT NOT NULL, created_at TEXT NOT NULL); CREATE INDEX sessions_user_idx ON sessions(user_id);
INSERT INTO missions (id,title,description,icon,metric,target,xp_reward,coin_reward,period,active,created_at,updated_at) VALUES
('water-2l','Hydration goal','Drink 2 liters of water','Droplets','water',2000,30,8,'daily',1,datetime('now'),datetime('now')),
('log-breakfast','Morning momentum','Log your breakfast','Sunrise','breakfast',1,20,5,'daily',1,datetime('now'),datetime('now')),
('protein-goal','Protein target','Reach your daily protein goal','Dumbbell','protein',100,40,10,'daily',1,datetime('now'),datetime('now')),
('all-meals','Full day logged','Log breakfast, lunch, and dinner','Utensils','meal_types',3,45,12,'daily',1,datetime('now'),datetime('now')),
('weekly-consistency','Consistent week','Log food on five days this week','CalendarCheck','active_days',5,100,25,'weekly',1,datetime('now'),datetime('now'));
INSERT INTO achievements (id,title,description,icon,metric,target,xp_reward,created_at,updated_at) VALUES
('first-meal','First Meal','Log your first meal','Utensils', 'meals',1,50,datetime('now'),datetime('now')),
('healthy-week','Healthy Week','Stay active for seven days','CalendarHeart','streak',7,150,datetime('now'),datetime('now')),
('protein-master','Protein Master','Reach protein target ten times','Dumbbell','protein_days',10,200,datetime('now'),datetime('now')),
('hydration-hero','Hydration Hero','Reach water target ten times','Droplets','water_days',10,200,datetime('now'),datetime('now')),
('consistency-king','Consistency King','Build a 30-day streak','Crown','streak',30,500,datetime('now'),datetime('now')),
('hundred-meals','100 Meals Logged','Log one hundred meals','Medal','meals',100,500,datetime('now'),datetime('now')),
('goal-weight','Goal Weight Achieved','Reach your target weight','Trophy','goal_weight',1,1000,datetime('now'),datetime('now'));
INSERT INTO foods (id,user_id,name,brand,serving_label,serving_grams,calories,protein,carbs,fat,is_favorite,use_count,created_at,updated_at) VALUES
('food-eggs',NULL,'Eggs','Whole','2 large eggs',100,143,13,1,10,0,0,datetime('now'),datetime('now')),
('food-oats',NULL,'Oatmeal','Rolled oats','50 g',50,190,6.5,34,3.5,0,0,datetime('now'),datetime('now')),
('food-chicken',NULL,'Chicken breast','Grilled','150 g',150,248,46,0,5,0,0,datetime('now'),datetime('now')),
('food-rice',NULL,'Basmati rice','Cooked','150 g',150,195,4,42,0.5,0,0,datetime('now'),datetime('now')),
('food-yogurt',NULL,'Greek yogurt','Plain 2%','170 g cup',170,130,17,8,4,0,0,datetime('now'),datetime('now')),
('food-banana',NULL,'Banana','Fresh','1 medium',118,105,1.3,27,0.4,0,0,datetime('now'),datetime('now'));
