import type { DashboardData, MealType } from '@nourish/shared';
import { motion } from 'framer-motion';
import { ChevronRight, Coins, Droplets, Flame, Plus, Sparkles, Utensils } from 'lucide-react';
import { IconFor, Metric, PageHeader, Pill, ProgressBar, Ring, SectionTitle } from '@/components/ui';
import { useAppStore } from '@/store/app';
import { compact, haptic } from '@/lib/utils';

const mealMeta:Record<MealType,{label:string;time:string;color:string}>={breakfast:{label:'Breakfast',time:'6:00 - 11:00',color:'bg-sun/15 text-[#a56b00]'},lunch:{label:'Lunch',time:'11:00 - 15:00',color:'bg-mint/15 text-[#168c72]'},dinner:{label:'Dinner',time:'17:00 - 22:00',color:'bg-blue/10 text-blue'},snack:{label:'Snacks',time:'Any time',color:'bg-coral/10 text-coral'}};
export function DashboardPage({data}:{data:DashboardData}){const {profile,progress,meals,missions,favoriteFoods}=data;const remaining=Math.max(0,profile.calorieTarget-progress.calories);const setWaterOpen=useAppStore(state=>state.setWaterOpen);const setAddMealOpen=useAppStore(state=>state.setAddMealOpen);const setTab=useAppStore(state=>state.setTab);const hour=new Date().getHours();const greeting=hour<12?'Good morning':hour<18?'Good afternoon':'Good evening';
return <div className="page">
<PageHeader eyebrow={new Intl.DateTimeFormat('en',{weekday:'long',month:'long',day:'numeric'}).format(new Date())} title={`${greeting}, ${profile.firstName}`} action={<button aria-label="Open profile" onClick={()=>setTab('profile')} className="h-11 w-11 overflow-hidden rounded-full border-2 border-white bg-blue text-sm font-bold text-white shadow-card">{profile.avatarUrl?<img src={profile.avatarUrl} alt="" className="h-full w-full object-cover"/>:profile.firstName.slice(0,1)}</button>}/>
<motion.section initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="card mb-4 overflow-hidden p-5">
<div className="mb-5 flex items-center justify-between"><div><p className="text-[13px] font-semibold subtle">Daily energy</p><p className="font-display text-[18px] font-bold">Calorie balance</p></div><Pill tone="yellow"><Flame size={13} fill="currentColor"/>{profile.currentStreak} day streak</Pill></div>
<div className="flex flex-col items-center gap-5 sm:flex-row sm:justify-around">
<Ring value={progress.calories} target={profile.calorieTarget} size={176} stroke={14}><div><p className="font-display text-[35px] font-extrabold leading-none">{compact(remaining)}</p><p className="mt-1 text-[12px] font-semibold subtle">kcal remaining</p></div></Ring>
<div className="grid w-full grid-cols-2 gap-3 sm:w-[190px] sm:grid-cols-1"><div className="rounded-lg bg-[#f3f7fb] p-3 dark:bg-[#202a35]"><p className="text-[11px] font-semibold subtle">Consumed</p><p className="mt-1 text-[20px] font-bold">{compact(progress.calories)}</p></div><div className="rounded-lg bg-[#f3f7fb] p-3 dark:bg-[#202a35]"><p className="text-[11px] font-semibold subtle">Daily target</p><p className="mt-1 text-[20px] font-bold">{compact(profile.calorieTarget)}</p></div></div>
</div>
<div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-3"><Metric label="Protein" value={progress.protein} target={profile.proteinTarget} unit="g" color="bg-coral"/><Metric label="Carbs" value={progress.carbs} target={profile.carbsTarget} unit="g" color="bg-sun"/><Metric label="Fat" value={progress.fat} target={profile.fatTarget} unit="g" color="bg-mint"/></div>
</motion.section>
<div className="mb-7 grid grid-cols-2 gap-3">
<motion.button whileTap={{scale:.98}} onClick={()=>{haptic();setWaterOpen(true)}} className="card p-4 text-left"><div className="mb-4 flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-blue/10 text-blue"><Droplets size={20}/></span><Plus size={18} className="subtle"/></div><p className="text-[12px] font-semibold subtle">Water</p><p className="font-display text-[22px] font-bold">{(progress.waterMl/1000).toFixed(1)}<span className="ml-1 text-[12px] font-medium subtle">/ {(profile.waterTargetMl/1000).toFixed(1)} L</span></p><ProgressBar value={progress.waterMl} target={profile.waterTargetMl} className="mt-3"/></motion.button>
<motion.button whileTap={{scale:.98}} onClick={()=>setTab('rewards')} className="card p-4 text-left"><div className="mb-4 flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-sun/15 text-[#a56b00]"><Sparkles size={20}/></span><Pill tone="yellow"><Coins size={12}/>{profile.coins}</Pill></div><p className="text-[12px] font-semibold subtle">Level {profile.level}</p><p className="font-display text-[22px] font-bold">{profile.xp}<span className="ml-1 text-[12px] font-medium subtle">XP total</span></p><ProgressBar value={profile.xp%300} target={300} color="bg-sun" className="mt-3"/></motion.button>
</div>
<SectionTitle title="Today's missions" action={<button onClick={()=>setTab('rewards')} className="text-[12px] font-bold text-blue">View all</button>}/>
<div className="no-scrollbar -mx-4 mb-7 flex gap-3 overflow-x-auto px-4 pb-2">{missions.slice(0,4).map((mission,index)=><motion.button onClick={()=>setTab('rewards')} initial={{opacity:0,x:16}} animate={{opacity:1,x:0}} transition={{delay:index*.06}} key={mission.id} className="card w-[225px] shrink-0 p-4 text-left"><div className="mb-4 flex items-center justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-full ${mission.completed?'bg-mint text-white':'bg-blue/10 text-blue'}`}><IconFor name={mission.icon} className="h-5 w-5"/></span><Pill tone={mission.completed?'green':'blue'}>+{mission.xpReward} XP</Pill></div><p className="font-display text-[15px] font-bold">{mission.title}</p><p className="mt-1 truncate text-[12px] subtle">{mission.description}</p><ProgressBar value={mission.progress} target={mission.target} color={mission.completed?'bg-mint':'bg-blue'} className="mt-4"/></motion.button>)}</div>
<SectionTitle title="Today's meals" action={<button onClick={()=>setAddMealOpen(true)} className="flex items-center gap-1 text-[12px] font-bold text-blue"><Plus size={15}/>Add</button>}/>
<div className="card mb-7 divide-y divide-[#edf1f5] overflow-hidden dark:divide-[#293541]">{(Object.keys(mealMeta) as MealType[]).map(type=>{const items=meals.filter(item=>item.mealType===type);const calories=items.reduce((sum,item)=>sum+item.calories,0);const meta=mealMeta[type];return <button key={type} onClick={()=>setAddMealOpen(true)} className="flex w-full items-center gap-3 p-4 text-left"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg ${meta.color}`}><Utensils size={18}/></span><span className="min-w-0 flex-1"><span className="flex items-center justify-between"><b className="text-[14px]">{meta.label}</b><span className="text-[13px] font-bold">{Math.round(calories)} kcal</span></span><span className="mt-0.5 block truncate text-[12px] subtle">{items.length?items.map(item=>item.name).join(', '):meta.time}</span></span><ChevronRight size={17} className="subtle"/></button>})}</div>
{favoriteFoods.length>0&&<><SectionTitle title="Favorites" action={<button onClick={()=>setTab('log')} className="text-[12px] font-bold text-blue">Browse</button>}/><div className="no-scrollbar -mx-4 flex gap-3 overflow-x-auto px-4 pb-3">{favoriteFoods.map(food=><button key={food.id} onClick={()=>setAddMealOpen(true)} className="card w-[165px] shrink-0 p-4 text-left"><span className="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-mint/10 text-mint"><Utensils size={18}/></span><p className="truncate text-[14px] font-bold">{food.name}</p><p className="mt-1 text-[12px] subtle">{food.calories} kcal ? {food.protein}g protein</p></button>)}</div></>}
</div>}
