import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import type { DashboardData, Food } from '@nourish/shared';
import { AnimatePresence, motion } from 'framer-motion';
import { Bookmark, Clock3, Heart, Plus, Search, Sparkles, Utensils } from 'lucide-react';
import { PageHeader, Pill, SectionTitle } from '@/components/ui';
import { cn } from '@/lib/utils';
import { useAppStore } from '@/store/app';
import { api } from '@/lib/api';

type FoodTab='search'|'favorites'|'recent'|'meals';
function FoodRow({food,onAdd}:{food:Food;onAdd:()=>void}){const queryClient=useQueryClient();const toggle=useMutation({mutationFn:()=>api.toggleFavorite(food.id),onSuccess:()=>{void queryClient.invalidateQueries({queryKey:['foods']});void queryClient.invalidateQueries({queryKey:['dashboard']})}});return <motion.div layout className="flex items-center border-b border-[#edf1f5] last:border-0 dark:border-[#293541]"><button onClick={onAdd} className="flex min-w-0 flex-1 items-center gap-3 px-4 py-3.5 text-left"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-blue/10 text-blue"><Utensils size={19}/></span><span className="min-w-0 flex-1"><span className="block truncate text-[14px] font-bold">{food.name}</span><span className="mt-0.5 block truncate text-[12px] subtle">{food.brand?food.brand+' · ':''}{food.servingLabel}</span></span><span className="text-right"><b className="block text-[14px]">{Math.round(food.calories)}</b><span className="text-[11px] subtle">kcal</span></span><Plus size={18} className="text-blue"/></button><button disabled={toggle.isPending} onClick={()=>toggle.mutate()} aria-label={food.isFavorite?'Remove favorite':'Add favorite'} className="mr-3 flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-coral"><Heart size={17} fill={food.isFavorite?'currentColor':'none'}/></button></motion.div>}
export function FoodPage({data}:{data:DashboardData}){const [tab,setTab]=useState<FoodTab>('search');const [query,setQuery]=useState('');const setAddMealOpen=useAppStore(state=>state.setAddMealOpen);const {data:allFoods=[]}=useQuery({queryKey:['foods','all'],queryFn:()=>api.foods('')});const source=tab==='favorites'?data.favoriteFoods:tab==='recent'?data.recentFoods:data.recentFoods;const foods=useMemo(()=>source.filter(food=>food.name.toLowerCase().includes(query.toLowerCase())),[source,query]);const tabItems=[{id:'search',label:'Search',icon:Search},{id:'favorites',label:'Favorites',icon:Heart},{id:'recent',label:'Recent',icon:Clock3},{id:'meals',label:'Saved',icon:Bookmark}] as const;
return <div className="page"><PageHeader eyebrow="Nutrition library" title="Log food" action={<button onClick={()=>setAddMealOpen(true)} aria-label="Create custom food" title="Create custom food" className="flex h-11 w-11 items-center justify-center rounded-full bg-blue text-white shadow-float"><Plus size={21}/></button>}/>
<div className="relative mb-4"><Search size={19} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 subtle"/><input value={query} onChange={event=>setQuery(event.target.value)} className="input pl-11 pr-4" placeholder="Search foods and meals" aria-label="Search foods"/></div>
<div className="no-scrollbar -mx-4 mb-6 flex gap-2 overflow-x-auto px-4">{tabItems.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setTab(item.id)} className={cn('flex h-10 shrink-0 items-center gap-2 rounded-full px-4 text-[13px] font-semibold transition-colors',tab===item.id?'bg-ink text-white dark:bg-white dark:text-ink':'bg-white subtle shadow-card dark:bg-[#1a222c]')}><Icon size={16}/>{item.label}</button>})}</div>
<div className="mb-6 grid grid-cols-2 gap-3"><button onClick={()=>setAddMealOpen(true)} className="card p-4 text-left"><span className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg bg-coral/10 text-coral"><Plus size={18}/></span><p className="text-[14px] font-bold">Quick calories</p><p className="mt-1 text-[12px] leading-4 subtle">Log calories without food details</p></button><button onClick={()=>setAddMealOpen(true)} className="card p-4 text-left"><span className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg bg-mint/10 text-mint"><Sparkles size={18}/></span><p className="text-[14px] font-bold">Custom food</p><p className="mt-1 text-[12px] leading-4 subtle">Create reusable nutrition</p></button></div>
<AnimatePresence mode="wait"><motion.div key={tab} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} exit={{opacity:0}}>{tab==='meals'?<SavedMeals foods={allFoods.filter(food=>food.brand==='Custom')} onAdd={()=>setAddMealOpen(true)}/>:<><SectionTitle title={tab==='favorites'?'Your favorites':tab==='recent'?'Recently logged':'Suggested foods'} action={<Pill tone="gray">{foods.length} items</Pill>}/><div className="card overflow-hidden">{foods.length?foods.map(food=><FoodRow key={food.id} food={food} onAdd={()=>setAddMealOpen(true)}/>):<div className="px-6 py-10 text-center"><Heart className="mx-auto mb-3 text-[#b8c2cd]" size={28}/><p className="font-bold">Nothing here yet</p><p className="mt-1 text-[13px] subtle">Foods you mark will appear here.</p></div>}</div></>}</motion.div></AnimatePresence>
</div>}
function SavedMeals({foods,onAdd}:{foods:Food[];onAdd:()=>void}){return <><SectionTitle title="Saved meals" action={<Pill tone="gray">{foods.length} meals</Pill>}/>{foods.length?<div className="card overflow-hidden">{foods.map(food=><FoodRow key={food.id} food={food} onAdd={onAdd}/>)}</div>:<div className="card px-6 py-10 text-center"><Bookmark className="mx-auto mb-3 text-[#b8c2cd]" size={28}/><p className="font-bold">No saved meals yet</p><p className="mx-auto mt-1 max-w-[260px] text-[13px] subtle">Create a custom food or combined meal to reuse it here.</p><button onClick={onAdd} className="mt-4 rounded-lg bg-blue px-4 py-2.5 text-[12px] font-bold text-white">Create saved meal</button></div>}</>}