import { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { Activity, ArrowLeft, ArrowRight, Check, Dumbbell, HeartPulse, Ruler, Scale, Sparkles, Target } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { calculateTargets, type ActivityLevel, type Goal } from '@nourish/shared';
import { api } from '@/lib/api';
import { cn } from '@/lib/utils';
import { Metric, Ring } from '@/components/ui';

const schema=z.object({age:z.coerce.number().int().min(13,'Enter an age from 13 to 100').max(100),gender:z.enum(['male','female','other']),heightCm:z.coerce.number().min(120).max(230),currentWeightKg:z.coerce.number().min(35).max(350),targetWeightKg:z.coerce.number().min(35).max(350),activityLevel:z.enum(['sedentary','light','moderate','high','athlete']),goal:z.enum(['lose','maintain','gain'])});
type Values=z.infer<typeof schema>;
const activities:{id:ActivityLevel;title:string;copy:string}[]=[{id:'sedentary',title:'Mostly seated',copy:'Little intentional exercise'},{id:'light',title:'Lightly active',copy:'1-3 workouts per week'},{id:'moderate',title:'Active',copy:'3-5 workouts per week'},{id:'high',title:'Very active',copy:'6-7 hard workouts'},{id:'athlete',title:'Athlete',copy:'Intense training or physical work'}];
const goals:{id:Goal;title:string;copy:string;icon:typeof Target}[]=[{id:'lose',title:'Lose weight',copy:'A steady, sustainable calorie deficit',icon:Target},{id:'maintain',title:'Maintain',copy:'Keep your current weight and feel strong',icon:HeartPulse},{id:'gain',title:'Gain weight',copy:'Build mass with a measured surplus',icon:Dumbbell}];
export function Onboarding(){const [step,setStep]=useState(0);const queryClient=useQueryClient();const {register,watch,setValue,trigger,handleSubmit,formState:{errors}}=useForm<Values>({resolver:zodResolver(schema),defaultValues:{age:29,gender:'male',heightCm:175,currentWeightKg:75,targetWeightKg:70,activityLevel:'moderate',goal:'lose'}});const values=watch();const targets=useMemo(()=>calculateTargets({age:Number(values.age)||29,gender:values.gender,heightCm:Number(values.heightCm)||175,weightKg:Number(values.currentWeightKg)||75,activity:values.activityLevel,goal:values.goal}),[values]);const mutation=useMutation({mutationFn:api.onboarding,onSuccess:()=>void queryClient.invalidateQueries({queryKey:['dashboard']})});const next=async()=>{const groups:(keyof Values)[][]=[['age','gender'],['heightCm','currentWeightKg','targetWeightKg'],['activityLevel','goal']];if(await trigger(groups[step]??[]))setStep(current=>Math.min(3,current+1))};
return <main className="app-shell !pb-0"><div className="page flex min-h-[100dvh] flex-col"><div className="mb-7 flex items-center justify-between"><button disabled={step===0} onClick={()=>setStep(current=>Math.max(0,current-1))} aria-label="Back" className="flex h-10 w-10 items-center justify-center rounded-full bg-white shadow-card disabled:opacity-0 dark:bg-[#1a222c]"><ArrowLeft size={19}/></button><div className="flex gap-1.5">{[0,1,2,3].map(index=><span key={index} className={cn('h-1.5 rounded-full transition-all',index===step?'w-7 bg-blue':index<step?'w-3 bg-mint':'w-3 bg-[#dce4ec] dark:bg-[#2d3945]')}/>)}</div><span className="w-10 text-right text-[12px] font-bold subtle">{step+1}/4</span></div>
<motion.div key={step} initial={{opacity:0,x:18}} animate={{opacity:1,x:0}} className="flex-1">{step===0&&<><Intro title="Let's personalize your plan" copy="A few details help us calculate targets that fit your body and routine." icon={<Sparkles/>}/><div className="card space-y-5 p-5"><Field label="Your age" error={errors.age?.message}><div className="relative"><input type="number" {...register('age')} className="input pr-16"/><span className="absolute right-4 top-1/2 -translate-y-1/2 text-[12px] subtle">years</span></div></Field><Field label="Gender"><div className="segmented grid-cols-3">{(['male','female','other'] as const).map(gender=><button type="button" key={gender} onClick={()=>setValue('gender',gender)} className={cn('h-11 rounded-md text-[13px] font-bold capitalize',values.gender===gender?'bg-white text-blue shadow-sm dark:bg-[#313d4a]':'subtle')}>{gender}</button>)}</div></Field></div></>}
{step===1&&<><Intro title="Your starting point" copy="Use current measurements. You can update them any time from your profile." icon={<Scale/>}/><div className="card space-y-5 p-5"><NumberField label="Height" unit="cm" icon={<Ruler/>} registration={register('heightCm')} error={errors.heightCm?.message}/><NumberField label="Current weight" unit="kg" icon={<Scale/>} registration={register('currentWeightKg')} error={errors.currentWeightKg?.message}/><NumberField label="Target weight" unit="kg" icon={<Target/>} registration={register('targetWeightKg')} error={errors.targetWeightKg?.message}/></div></>}
{step===2&&<><Intro title="Shape your daily plan" copy="Choose the routine and goal that best reflect your life right now." icon={<Activity/>}/><p className="mb-2 text-[12px] font-bold subtle">ACTIVITY LEVEL</p><div className="card mb-5 overflow-hidden">{activities.map(item=><button type="button" key={item.id} onClick={()=>setValue('activityLevel',item.id)} className="flex w-full items-center gap-3 border-b border-[#edf1f5] p-4 text-left last:border-0 dark:border-[#293541]"><span className={cn('flex h-6 w-6 items-center justify-center rounded-full border-2',values.activityLevel===item.id?'border-blue bg-blue text-white':'border-[#d4dde6]')} >{values.activityLevel===item.id&&<Check size={13} strokeWidth={3}/>}</span><span><b className="block text-[13px]">{item.title}</b><span className="text-[11px] subtle">{item.copy}</span></span></button>)}</div><p className="mb-2 text-[12px] font-bold subtle">YOUR GOAL</p><div className="grid gap-3">{goals.map(item=>{const Icon=item.icon;return <button type="button" key={item.id} onClick={()=>setValue('goal',item.id)} className={cn('card flex items-center gap-4 p-4 text-left',values.goal===item.id&&'border-blue ring-2 ring-blue/15')}><span className={cn('flex h-11 w-11 items-center justify-center rounded-lg',values.goal===item.id?'bg-blue text-white':'bg-blue/10 text-blue')}><Icon size={20}/></span><span><b className="block text-[14px]">{item.title}</b><span className="text-[11px] subtle">{item.copy}</span></span></button>})}</div></>}
{step===3&&<><Intro title="Your plan is ready" copy="Built from your metabolism, activity level, and goal. These targets can evolve with you." icon={<Sparkles/>}/><section className="card mb-4 p-5"><div className="flex justify-center"><Ring value={targets.calories} target={targets.calories} size={172} color="#2787f5"><div><p className="font-display text-[36px] font-extrabold leading-none">{targets.calories}</p><p className="mt-1 text-[12px] font-semibold subtle">kcal per day</p></div></Ring></div><div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-3"><Metric label="Protein" value={targets.protein} target={targets.protein} unit="g" color="bg-coral"/><Metric label="Carbs" value={targets.carbs} target={targets.carbs} unit="g" color="bg-sun"/><Metric label="Fat" value={targets.fat} target={targets.fat} unit="g" color="bg-mint"/></div></section><div className="grid grid-cols-2 gap-3"><div className="card p-4"><p className="text-[11px] font-semibold subtle">Water goal</p><p className="mt-1 font-display text-[21px] font-extrabold">{(targets.waterMl/1000).toFixed(1)} L</p></div><div className="card p-4"><p className="text-[11px] font-semibold subtle">Target weight</p><p className="mt-1 font-display text-[21px] font-extrabold">{values.targetWeightKg} kg</p></div></div>{mutation.isError&&<p className="mt-4 text-center text-[12px] font-semibold text-coral">Could not save your plan. Check the Worker connection.</p>}</>}</motion.div>
<div className="pt-6">{step<3?<button onClick={next} className="flex h-14 w-full items-center justify-center gap-2 rounded-lg bg-blue font-bold text-white shadow-float">Continue<ArrowRight size={18}/></button>:<button disabled={mutation.isPending} onClick={handleSubmit(values=>mutation.mutate(values))} className="flex h-14 w-full items-center justify-center gap-2 rounded-lg bg-blue font-bold text-white shadow-float disabled:opacity-60">{mutation.isPending?'Saving your plan?':'Start my journey'}<Check size={18}/></button>}</div></div></main>}
function Intro({title,copy,icon}:{title:string;copy:string;icon:React.ReactNode}){return <div className="mb-7 text-center"><span className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-blue/10 text-blue [&>svg]:h-6 [&>svg]:w-6">{icon}</span><h1 className="font-display text-[27px] font-extrabold leading-tight">{title}</h1><p className="mx-auto mt-2 max-w-[360px] text-[13px] leading-5 subtle">{copy}</p></div>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label><span className="mb-2 block text-[12px] font-bold">{label}</span>{children}{error&&<span className="mt-1 block text-[11px] text-coral">{error}</span>}</label>}
function NumberField({label,unit,icon,registration,error}:{label:string;unit:string;icon:React.ReactNode;registration:ReturnType<ReturnType<typeof useForm<Values>>['register']>;error?:string}){return <Field label={label} error={error}><div className="relative"><span className="absolute left-4 top-1/2 -translate-y-1/2 subtle [&>svg]:h-[18px] [&>svg]:w-[18px]">{icon}</span><input type="number" step=".1" {...registration} className="input pl-11 pr-14"/><span className="absolute right-4 top-1/2 -translate-y-1/2 text-[12px] subtle">{unit}</span></div></Field>}
