import { useState } from 'react';
import type { DashboardData } from '@nourish/shared';
import { useMutation } from '@tanstack/react-query';
import { Bell, ChevronRight, CircleUserRound, Download, Droplets, Flame, Globe2, Moon, Ruler, Scale, Shield, Sun, Target, Trash2, Trophy } from 'lucide-react';
import { api } from '@/lib/api';
import { PageHeader, Pill, ProgressBar, SectionTitle, Toggle } from '@/components/ui';
import { cn } from '@/lib/utils';
import { useAppStore } from '@/store/app';

export function ProfilePage({data}:{data:DashboardData}){const profile=data.profile;const theme=useAppStore(state=>state.theme);const setTheme=useAppStore(state=>state.setTheme);const showToast=useAppStore(state=>state.showToast);const [units,setUnits]=useState<'metric'|'imperial'>('metric');const [reminders,setReminders]=useState({daily:true,water:true,calorie:true,streak:true});const exportMutation=useMutation({mutationFn:api.exportData,onSuccess:(payload)=>{const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=`nourish-export-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url);showToast('Export downloaded')},onError:()=>showToast('Connect the Worker to export data')});const deleteMutation=useMutation({mutationFn:api.deleteAccount,onSuccess:()=>{showToast('Your data was deleted');setTimeout(()=>window.Telegram?.WebApp?.close(),900)},onError:()=>showToast('Connect the Worker to delete data')});const updateReminder=(key:keyof typeof reminders,value:boolean)=>{setReminders(current=>({...current,[key]:value}));void api.updateSettings({[`${key}Reminder`]:value}).catch(()=>undefined)};
return <div className="page"><PageHeader eyebrow="Your account" title="Profile" action={<button aria-label="Profile options" className="flex h-10 w-10 items-center justify-center rounded-full bg-white shadow-card dark:bg-[#1a222c]"><CircleUserRound size={21}/></button>}/>
<section className="card mb-4 p-5"><div className="flex items-center gap-4"><div className="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-full bg-blue font-display text-[24px] font-extrabold text-white">{profile.avatarUrl?<img src={profile.avatarUrl} alt="" className="h-full w-full object-cover"/>:profile.firstName.slice(0,1)}</div><div className="min-w-0 flex-1"><h2 className="truncate font-display text-[20px] font-extrabold">{profile.firstName}{profile.lastName?` ${profile.lastName}`:''}</h2><p className="mt-0.5 truncate text-[12px] subtle">{profile.username?`@${profile.username}`:'Telegram member'}</p><div className="mt-2 flex gap-2"><Pill tone="blue">Level {profile.level}</Pill><Pill tone="yellow"><Flame size={12}/>{profile.currentStreak} days</Pill></div></div></div><div className="mt-5"><div className="mb-2 flex justify-between text-[11px] font-semibold"><span className="subtle">Level progress</span><span>{profile.xp} XP</span></div><ProgressBar value={profile.xp%300} target={300}/></div></section>
<div className="mb-7 grid grid-cols-3 gap-3"><ProfileStat icon={<Scale/>} label="Weight" value={`${profile.currentWeightKg} kg`}/><ProfileStat icon={<Target/>} label="Goal" value={profile.goal==='lose'?'Lose weight':profile.goal==='gain'?'Gain weight':'Maintain'}/><ProfileStat icon={<Trophy/>} label="Badges" value={String(data.achievements.filter(item=>item.unlockedAt).length)}/></div>
<SectionTitle title="Appearance"/><section className="card mb-6 p-4"><p className="mb-3 text-[12px] font-semibold subtle">Theme</p><div className="segmented grid-cols-3">{([{id:'light',label:'Light',icon:Sun},{id:'dark',label:'Dark',icon:Moon},{id:'system',label:'System',icon:Shield}] as const).map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setTheme(item.id)} className={cn('flex h-10 items-center justify-center gap-1.5 rounded-md text-[12px] font-bold',theme===item.id?'bg-white text-blue shadow-sm dark:bg-[#313d4a]':'subtle')}><Icon size={15}/>{item.label}</button>})}</div></section>
<SectionTitle title="Preferences"/><section className="card mb-6 overflow-hidden"><SettingRow icon={<Ruler/>} title="Units" copy="Weight, height, and water"><div className="flex rounded-lg bg-[#edf1f5] p-1 dark:bg-[#26313d]">{(['metric','imperial'] as const).map(item=><button key={item} onClick={()=>setUnits(item)} className={cn('rounded-md px-2.5 py-1.5 text-[11px] font-bold capitalize',units===item?'bg-white shadow-sm dark:bg-[#354250]':'subtle')}>{item}</button>)}</div></SettingRow><SettingRow icon={<Globe2/>} title="Language" copy="Architecture ready for localization"><button className="flex items-center gap-1 text-[12px] font-bold">English<ChevronRight size={15} className="subtle"/></button></SettingRow></section>
<SectionTitle title="Reminders"/><section className="card mb-6 overflow-hidden"><SettingRow icon={<Bell/>} title="Daily check-in" copy="Morning plan and motivation"><Toggle label="Daily reminder" checked={reminders.daily} onChange={value=>updateReminder('daily',value)}/></SettingRow><SettingRow icon={<Droplets/>} title="Water reminder" copy="Gentle afternoon hydration nudge"><Toggle label="Water reminder" checked={reminders.water} onChange={value=>updateReminder('water',value)}/></SettingRow><SettingRow icon={<Target/>} title="Calorie reminder" copy="End-of-day target check"><Toggle label="Calorie reminder" checked={reminders.calorie} onChange={value=>updateReminder('calorie',value)}/></SettingRow><SettingRow icon={<Flame/>} title="Streak warning" copy="Alert before your streak expires"><Toggle label="Streak warning" checked={reminders.streak} onChange={value=>updateReminder('streak',value)}/></SettingRow></section>
<SectionTitle title="Your data"/><section className="card mb-6 overflow-hidden"><button onClick={()=>exportMutation.mutate()} className="flex w-full items-center gap-3 border-b border-[#edf1f5] p-4 text-left dark:border-[#293541]"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-blue/10 text-blue"><Download size={18}/></span><span className="flex-1"><b className="block text-[13px]">Export all data</b><span className="text-[11px] subtle">Download a complete JSON backup</span></span><ChevronRight size={17} className="subtle"/></button><button onClick={()=>{if(confirm('Delete all Nourish data? This cannot be undone.'))deleteMutation.mutate()}} className="flex w-full items-center gap-3 p-4 text-left text-[#d74747]"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#ffecec] dark:bg-[#3b2529]"><Trash2 size={18}/></span><span className="flex-1"><b className="block text-[13px]">Delete all data</b><span className="text-[11px] text-[#d97a7a]">Permanently remove your account</span></span><ChevronRight size={17}/></button></section>
<p className="pb-2 text-center text-[11px] subtle">Nourish 1.0 ? Built for Telegram</p></div>}
function SettingRow({icon,title,copy,children}:{icon:React.ReactNode;title:string;copy:string;children:React.ReactNode}){return <div className="flex items-center gap-3 border-b border-[#edf1f5] p-4 last:border-0 dark:border-[#293541]"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[#eef3f7] subtle [&>svg]:h-[17px] [&>svg]:w-[17px] dark:bg-[#26313d]">{icon}</span><span className="min-w-0 flex-1"><b className="block text-[13px]">{title}</b><span className="block truncate text-[11px] subtle">{copy}</span></span>{children}</div>}
function ProfileStat({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="card min-w-0 p-3 text-center"><span className="mx-auto mb-2 flex h-8 w-8 items-center justify-center rounded-full bg-blue/10 text-blue [&>svg]:h-[16px] [&>svg]:w-[16px]">{icon}</span><p className="truncate text-[12px] font-bold">{value}</p><p className="mt-0.5 text-[10px] subtle">{label}</p></div>}
