import { useMemo, useState } from 'react';
import type { DashboardData } from '@nourish/shared';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { Activity, ArrowDownRight, CalendarDays, Droplets, Plus, Scale, Target } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { api } from '@/lib/api';
import { PageHeader, Pill, SectionTitle } from '@/components/ui';
import { cn } from '@/lib/utils';
import { useAppStore } from '@/store/app';

type Period=7|30|90; type Metric='calories'|'protein'|'carbs'|'fat'|'waterMl';
const metricMeta:Record<Metric,{label:string;color:string;unit:string}>={calories:{label:'Calories',color:'#2787f5',unit:'kcal'},protein:{label:'Protein',color:'#ff7a6d',unit:'g'},carbs:{label:'Carbs',color:'#ffbb3d',unit:'g'},fat:{label:'Fat',color:'#40c6a2',unit:'g'},waterMl:{label:'Water',color:'#62b6ff',unit:'ml'}};
export function ProgressPage({data}:{data:DashboardData}){const [period,setPeriod]=useState<Period>(7);const [metric,setMetric]=useState<Metric>('calories');const [weight,setWeight]=useState(String(data.profile.currentWeightKg??''));const queryClient=useQueryClient();const showToast=useAppStore(state=>state.showToast);const {data:stats}=useQuery({queryKey:['stats',period],queryFn:()=>api.stats(period)});const addWeight=useMutation({mutationFn:()=>api.addWeight(Number(weight)),onSuccess:()=>{void queryClient.invalidateQueries({queryKey:['dashboard']});void queryClient.invalidateQueries({queryKey:['stats']});showToast('Weight logged')},onError:()=>showToast('Connect the Worker to save weight')});const rows=useMemo(()=>stats?.days??[],[stats?.days]);const weights=useMemo(()=>stats?.weights??[],[stats?.weights]);const averages=useMemo(()=>{const divisor=Math.max(1,rows.length);return {calories:Math.round(rows.reduce((sum,row)=>sum+row.calories,0)/divisor),protein:Math.round(rows.reduce((sum,row)=>sum+row.protein,0)/divisor),water:Math.round(rows.reduce((sum,row)=>sum+row.waterMl,0)/divisor),consistency:Math.round(rows.filter(row=>row.calories>0).length/divisor*100)}},[rows]);const weightAverage=weights.length?weights.reduce((sum,row)=>sum+row.weightKg,0)/weights.length:0;const weightChange=weights.length>1?weights[weights.length-1].weightKg-weights[0].weightKg:0;const chartRows=rows.map(row=>({...row,label:new Date(row.date+'T12:00:00').toLocaleDateString('en',{weekday:period===7?'short':undefined,month:'short',day:'numeric'})}));const color=metricMeta[metric].color;
return <div className="page"><PageHeader eyebrow="Health insights" title="Your progress" action={<Pill tone="green"><Activity size={13}/>On track</Pill>}/>
<div className="segmented mb-6 grid-cols-3">{([7,30,90] as Period[]).map(value=><button key={value} onClick={()=>setPeriod(value)} className={cn('h-9 rounded-md text-[13px] font-bold transition-all',period===value?'bg-white text-ink shadow-sm dark:bg-[#313d4a] dark:text-white':'subtle')}>{value===7?'Week':value===30?'Month':'3 months'}</button>)}</div>
<section className="card mb-4 p-4"><div className="mb-4 flex items-center justify-between"><div><p className="text-[12px] font-semibold subtle">{metricMeta[metric].label} trend</p><p className="font-display text-[24px] font-extrabold">{metric==='calories'?averages.calories:metric==='protein'?averages.protein:metric==='waterMl'?averages.water:Math.round(rows.reduce((sum,row)=>sum+row[metric],0)/Math.max(1,rows.length))}<span className="ml-1 text-[12px] font-semibold subtle">{metricMeta[metric].unit} avg</span></p></div><Pill tone="blue">{period} days</Pill></div>
<div className="h-[220px] w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartRows} margin={{left:-25,right:5,top:10,bottom:0}}><defs><linearGradient id="metricFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={color} stopOpacity={.25}/><stop offset="100%" stopColor={color} stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e7edf3" strokeDasharray="3 4"/><XAxis dataKey="label" tick={{fontSize:10,fill:'#8b96a3'}} axisLine={false} tickLine={false} interval="preserveStartEnd"/><YAxis tick={{fontSize:10,fill:'#8b96a3'}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:8,border:'1px solid #e4eaf0',fontSize:12}}/><Area type="monotone" dataKey={metric} stroke={color} strokeWidth={3} fill="url(#metricFill)" activeDot={{r:5}}/></AreaChart></ResponsiveContainer></div>
<div className="no-scrollbar mt-2 flex gap-2 overflow-x-auto">{(Object.keys(metricMeta) as Metric[]).map(item=><button key={item} onClick={()=>setMetric(item)} className={cn('shrink-0 rounded-full px-3 py-1.5 text-[11px] font-bold',metric===item?'text-white':'bg-[#eef3f7] subtle dark:bg-[#27313c]')} style={metric===item?{backgroundColor:metricMeta[item].color}:undefined}>{metricMeta[item].label}</button>)}</div></section>
<div className="mb-7 grid grid-cols-2 gap-3"><Stat icon={<Target/>} label="Consistency" value={`${averages.consistency}%`} copy="days logged" tone="text-blue bg-blue/10"/><Stat icon={<CalendarDays/>} label="Avg calories" value={String(averages.calories)} copy="kcal per day" tone="text-coral bg-coral/10"/><Stat icon={<Activity/>} label="Avg protein" value={`${averages.protein}g`} copy="per day" tone="text-mint bg-mint/10"/><Stat icon={<Droplets/>} label="Avg water" value={`${(averages.water/1000).toFixed(1)}L`} copy="per day" tone="text-[#2a9dd6] bg-sky/10"/></div>
<SectionTitle title="Weight trend" action={<Pill tone={weightChange<=0?'green':'yellow'}><ArrowDownRight size={13}/>{weightChange>0?'+':''}{weightChange.toFixed(1)} kg</Pill>}/>
<section className="card mb-4 overflow-hidden"><div className="grid grid-cols-[1fr_auto] gap-3 border-b border-[#edf1f5] p-4 dark:border-[#293541]"><label><span className="mb-2 block text-[12px] font-semibold subtle">Log today's weight</span><div className="relative"><Scale size={18} className="absolute left-3 top-1/2 -translate-y-1/2 subtle"/><input type="number" step=".1" value={weight} onChange={event=>setWeight(event.target.value)} className="input pl-10 pr-10"/><span className="absolute right-3 top-1/2 -translate-y-1/2 text-[12px] subtle">kg</span></div></label><button disabled={addWeight.isPending||!Number(weight)} onClick={()=>addWeight.mutate()} aria-label="Add weight" className="mt-[26px] flex h-[50px] w-[50px] items-center justify-center rounded-lg bg-blue text-white disabled:opacity-50"><Plus size={20}/></button></div>
<div className="grid grid-cols-2 px-4 pt-4"><div><p className="text-[11px] font-semibold subtle">{period===7?'Weekly':'Period'} average</p><p className="mt-1 text-[21px] font-extrabold">{weightAverage.toFixed(1)} kg</p></div><div className="text-right"><p className="text-[11px] font-semibold subtle">Goal</p><p className="mt-1 text-[21px] font-extrabold">{data.profile.targetWeightKg} kg</p></div></div>
<div className="h-[180px] w-full px-2 pb-3"><ResponsiveContainer width="100%" height="100%"><LineChart data={weights.map(item=>({...item,label:new Date(item.loggedAt).toLocaleDateString('en',{month:'short',day:'numeric'})}))} margin={{left:-25,right:8,top:20,bottom:0}}><CartesianGrid vertical={false} stroke="#e7edf3" strokeDasharray="3 4"/><XAxis dataKey="label" tick={{fontSize:10,fill:'#8b96a3'}} axisLine={false} tickLine={false} interval="preserveStartEnd"/><YAxis domain={['dataMin - 1','dataMax + 1']} tick={{fontSize:10,fill:'#8b96a3'}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{borderRadius:8,border:'1px solid #e4eaf0',fontSize:12}}/><Line type="monotone" dataKey="weightKg" stroke="#40c6a2" strokeWidth={3} dot={false} activeDot={{r:5}}/></LineChart></ResponsiveContainer></div></section>
<SectionTitle title="Calorie consistency"/><section className="card p-4"><div className="h-[150px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={chartRows} margin={{left:-30,right:0,top:5,bottom:0}}><XAxis dataKey="label" tick={{fontSize:9,fill:'#8b96a3'}} axisLine={false} tickLine={false} interval="preserveStartEnd"/><YAxis hide/><Tooltip contentStyle={{borderRadius:8,border:'1px solid #e4eaf0',fontSize:12}}/><Bar dataKey="calories" fill="#2787f5" radius={[4,4,0,0]} maxBarSize={16}/></BarChart></ResponsiveContainer></div></section>
</div>}
function Stat({icon,label,value,copy,tone}:{icon:React.ReactNode;label:string;value:string;copy:string;tone:string}){return <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="card p-4"><span className={cn('mb-4 flex h-9 w-9 items-center justify-center rounded-lg [&>svg]:h-[18px] [&>svg]:w-[18px]',tone)}>{icon}</span><p className="text-[11px] font-semibold subtle">{label}</p><p className="mt-1 font-display text-[21px] font-extrabold">{value}</p><p className="mt-0.5 text-[11px] subtle">{copy}</p></motion.div>}
