import type { DashboardData } from '@nourish/shared';
import { motion } from 'framer-motion';
import { CalendarCheck, Check, Coins, Flame, Gift, LockKeyhole, Sparkles, Star, Trophy } from 'lucide-react';
import { LEVELS, xpToNextLevel } from '@nourish/shared';
import { CompletedMark, IconFor, PageHeader, Pill, ProgressBar, SectionTitle } from '@/components/ui';

export function RewardsPage({data}:{data:DashboardData}){const {profile,missions,achievements}=data;const next=xpToNextLevel(profile.xp);const currentFloor=LEVELS[Math.max(0,profile.level-1)]??0;const levelProgress=profile.xp-currentFloor;const levelTarget=next-currentFloor;const daily=missions.filter(mission=>mission.period==='daily');const weekly=missions.filter(mission=>mission.period==='weekly');
return <div className="page"><PageHeader eyebrow="Your momentum" title="Rewards" action={<Pill tone="yellow"><Coins size={13}/>{profile.coins}</Pill>}/>
<section className="card relative mb-4 overflow-hidden p-5"><div className="absolute right-0 top-0 h-24 w-24 rounded-bl-full bg-blue/10"/><div className="relative flex items-center gap-4"><div className="flex h-16 w-16 shrink-0 items-center justify-center rounded-full bg-blue text-white shadow-float"><span className="font-display text-[24px] font-extrabold">{profile.level}</span></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between"><div><p className="text-[12px] font-semibold text-blue">LEVEL {profile.level}</p><h2 className="font-display text-[20px] font-extrabold">{levelName(profile.level)}</h2></div><Pill tone="blue">{profile.xp} XP</Pill></div><ProgressBar value={levelProgress} target={levelTarget} className="mt-3"/><p className="mt-2 text-[11px] subtle">{Math.max(0,next-profile.xp)} XP until level {profile.level+1}</p></div></div></section>
<div className="mb-7 grid grid-cols-3 gap-3"><MiniStat icon={<Flame/>} value={profile.currentStreak} label="Day streak" tone="text-coral bg-coral/10"/><MiniStat icon={<Trophy/>} value={profile.longestStreak} label="Best streak" tone="text-sun bg-sun/15"/><MiniStat icon={<Star/>} value={achievements.filter(item=>item.unlockedAt).length} label="Badges" tone="text-mint bg-mint/10"/></div>
<motion.section whileTap={{scale:.99}} className="mb-7 flex items-center gap-4 rounded-lg border border-blue/15 bg-blue px-5 py-4 text-white shadow-float"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-white/18"><Gift size={23}/></span><span className="min-w-0 flex-1"><b className="font-display text-[16px]">Daily reward ready</b><span className="mt-0.5 block text-[12px] text-white/75">Open Nourish daily to grow your streak.</span></span><span className="rounded-full bg-white px-3 py-1.5 text-[12px] font-extrabold text-blue">+15 XP</span></motion.section>
<SectionTitle title="Daily missions" action={<Pill tone="gray">{daily.filter(item=>item.completed).length}/{daily.length}</Pill>}/><div className="card mb-7 divide-y divide-[#edf1f5] overflow-hidden dark:divide-[#293541]">{daily.map((mission,index)=><MissionRow key={mission.id} mission={mission} index={index}/>)}</div>
{weekly.length>0&&<><SectionTitle title="Weekly missions" action={<Pill tone="blue"><CalendarCheck size={13}/>Resets Monday</Pill>}/><div className="card mb-7 divide-y divide-[#edf1f5] overflow-hidden dark:divide-[#293541]">{weekly.map((mission,index)=><MissionRow key={mission.id} mission={mission} index={index}/>)}</div></>}
<SectionTitle title="Achievements" action={<Pill tone="yellow"><Sparkles size={13}/>{achievements.filter(item=>item.unlockedAt).length} earned</Pill>}/><div className="grid grid-cols-2 gap-3">{achievements.map((achievement,index)=>{const unlocked=Boolean(achievement.unlockedAt);return <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:index*.04}} key={achievement.id} className={`card relative min-h-[178px] overflow-hidden p-4 ${unlocked?'':'opacity-65'}`}><div className={`mb-4 flex h-12 w-12 items-center justify-center rounded-full ${unlocked?'bg-sun/15 text-[#a56b00]':'bg-[#edf1f5] subtle dark:bg-[#28333f]'}`}>{unlocked?<IconFor name={achievement.icon} className="h-6 w-6"/>:<LockKeyhole size={20}/>}</div><h3 className="font-display text-[14px] font-bold">{achievement.title}</h3><p className="mt-1 text-[11px] leading-4 subtle">{achievement.description}</p><div className="absolute bottom-4 left-4 right-4 flex items-center justify-between"><Pill tone={unlocked?'yellow':'gray'}>+{achievement.xpReward} XP</Pill>{unlocked&&<span className="flex h-6 w-6 items-center justify-center rounded-full bg-mint text-white"><Check size={14} strokeWidth={3}/></span>}</div></motion.div>})}</div>
</div>}
function MissionRow({mission,index}:{mission:DashboardData['missions'][number];index:number}){return <motion.div initial={{opacity:0,x:8}} animate={{opacity:1,x:0}} transition={{delay:index*.04}} className="flex items-center gap-3 p-4"><span className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-lg ${mission.completed?'bg-mint text-white':'bg-blue/10 text-blue'}`}><IconFor name={mission.icon} className="h-5 w-5"/></span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><b className="truncate text-[14px]">{mission.title}</b><span className="shrink-0 text-[11px] font-bold text-blue">+{mission.xpReward} XP</span></span><span className="mt-1 block truncate text-[11px] subtle">{mission.description}</span><ProgressBar value={mission.progress} target={mission.target} color={mission.completed?'bg-mint':'bg-blue'} className="mt-2"/></span>{mission.completed&&<CompletedMark/>}</motion.div>}
function MiniStat({icon,value,label,tone}:{icon:React.ReactNode;value:number;label:string;tone:string}){return <div className="card px-2 py-4 text-center"><span className={`mx-auto mb-2 flex h-9 w-9 items-center justify-center rounded-full [&>svg]:h-[18px] [&>svg]:w-[18px] ${tone}`}>{icon}</span><p className="font-display text-[20px] font-extrabold">{value}</p><p className="mt-0.5 text-[10px] font-semibold subtle">{label}</p></div>}
function levelName(level:number){if(level>=10)return 'Nourish Legend';if(level>=7)return 'Wellness Pro';if(level>=4)return 'Habit Builder';return 'Fresh Starter'}
